### ISSUE TITLE
Look into porting this to Microsoft Edge

### ISSUE THREAD

**Issue by rik-smeets** [infokiller/google-search-navigator#14]
I will look into this when I have time (probably in about 1-2 weeks).

**Comment by rik-smeets** [comment]
I made a working version of this on my local machine. I only needed to change the CSS and add an "Author" to the manifest file. However, packaging for the Windows Store is of course very different. How would you like to handle this @infokiller? 

I could just open a PR for those two changes, which should also be compatible with Google Chrome (I will test this beforehand of course), and package the extension myself and take responsibility for uploading it to the Windows Store. I already have a Microsoft Developer account and experience with adding packages to the Windows Store. But if you would like to do this yourself too, that's fine of course, please let me know.

**Comment by infokiller** [comment]
Thanks for doing this @rik-smeets !
I very rarely run windows on my machine these days, so if you can open the PR and package it yourself that would be great. Also worth mentioning that Edge is not "officially" supported (at least I won't be able to respond to issues in a reasonable time).

Side note: feel free to add yourself as an author or give yourself credit wherever you want (README, manifest, whatever)- you have a lot of contributions already. I will do it at some point anyway. In about 3-4 weeks I plan to do a round of improvements, so will probably take care of it then.

**Comment by rik-smeets** [comment]
It's been a while, but I'm ready to pick this up again.

Since then, I found out I can't change the publisher name of a single app package. This would mean that if I would publish the extension to the Microsoft Store, the publisher name would just be my name. Of course, I would refer to this repository, but still... It doesn't feel like doing justice to all contributors here, since I've only had a minor part in it's development.

I'll try to find how this is handled for other open source extensions, maybe there is some way. I wonder what your ideas about this are @infokiller?

**Comment by infokiller** [comment]
Hmm, I don't have a good idea on how to handle this, but I'm fine with the publisher name being yours, as long as this repo is referenced.
