### ISSUE TITLE
Pressing any character keystroke to append to search query

### ISSUE THREAD

**Issue by madsonic** [infokiller/google-search-navigator#19]
Google used to have this shortcut along with the navigation that you made. If we can type any character to bring focus back to the search box it would make searching really awesome again

**Comment by mancze** [comment]
That sounds interesting. Currently the search box is focused upon pressing `Esc` key but all text in the search box is selected. Perhaps adding an option whether text should or should not be selected should be added? The behavior would be almost the same as you describe only requiring one extra key to be pressed.

**Comment by marscos** [comment]
This sounds a lot like [this issue](https://github.com/infokiller/google-search-navigator/issues/3). I thought of the `Esc`/`/` shortcut too, but though very similar, surely it's not the behaviour you want. You both mentioned the late Google Instant on this. Perhaps the best way to achieve this would be adding something like a "Google Instant Mode" to the options menu?

**Comment by madsonic** [comment]
Yes the idea is same as #3. Probably should have looked first. I had no clue <kbd>Esc</kbd> and <kbd>/</kbd> could focus the searchbox. Thanks. Will close this to reduce duplicate
