### ISSUE TITLE
Input search box not being focused when image is previewed in the Images tab

### ISSUE THREAD

**Issue by marscos** [infokiller/google-search-navigator#28]
After selecting and previewing an image in the Images tab, like this:
![image](https://user-images.githubusercontent.com/15524244/32600621-57434a18-c527-11e7-8fd5-bef5d0bc2c8e.png)
Pressing the keybind to focus on the input search box does nothing.

**Comment by rik-smeets** [comment]
I cannot reproduce this (using the version currently in the Chrome Web Store). Are you using a different version perhaps?

**Comment by marscos** [comment]
Yeah, you're right. That was my bad. Also, sorry for taking so long to reply.
