### ISSUE TITLE
Refactor core to more command-based pattern

### ISSUE THREAD

**Issue by mancze** [infokiller/google-search-navigator#31]
Current core functionality of the extension is attached as direct handlers of the keymaster events. This causes me problems when debugging/fiddling around with the extension. For example it is not easy to invoke "navigate to the next result" command directly from the developer console.

I would like to refactor the main script of the extension to be more "object" oriented. I think it will provide many benefits aside from what I mentioned. I imagine the core somewhat like:

```js
const extension = {
  options: { },

  init: function() {
    // ...
  },

  commands: {
    focusNextResult: function() {
      // ...
    },
    focusPreviousResult: function() {
      // ...
    },
  }
};

extension.init();
```

What do you think about this? I would implement that but I want to discuss it first.

**Comment by infokiller** [comment]
I think it's a good idea! feel free to send a PR.

**Comment by afilp** [comment]
@mancze Great indeed! My plus vote to proceed to a PR if you have the time!

**Comment by mancze** [comment]
I want just to confirm that I'm still working on this and I'm done with the major part. Now just some final polishing and it will be ready. I must admit I have maybe got I little more involved than needed and the code-base now looks pretty different. Yet I hope it is toward better code organization and reuse.
