### ISSUE TITLE
Support jumping to more tabs (or more urls)

### ISSUE THREAD

**Issue by tedzhu** [infokiller/google-search-navigator#32]
It'd be nice to support all tabs, including shopping, books, flights, etc.

More generally, maybe support customizing the url to jump, using the current query word. Now this could be debatable since it is similar to what browser is sort of doing, e.g. chrome://settings/searchEngines. But it'd be really nice to have this search google first then go to other sites workflow.

Anyway really appreciate this work, did what google should be doing for decades.

**Comment by mancze** [comment]
Regarding ability to navigate tabs easily I mentioned something already in https://github.com/infokiller/google-search-navigator/issues/30#issuecomment-344973215, so this might be related to said issue.
