### ISSUE TITLE
Ctrl+Return opens two tabs on the side

### ISSUE THREAD

**Issue by Otiel** [infokiller/google-search-navigator#41]
When I use the shortcut <kbd>Ctrl</kbd><kbd>Return</kbd>, two tabs instead of one are opened on the side. This bug doesn't happen when I use <kbd>Ctrl</kbd><kbd>Space</kbd>.

_Firefox 59.0.1, Windows 10 64 bit_

**Comment by mancze** [comment]
This should be fixed in #38 already. I just didn't release new version yet. I should get to it within this week.

**Comment by mancze** [comment]
Finally released new version. @Otiel Can you test the issue is fixed?

**Comment by Otiel** [comment]
Tested and confirmed that this is fixed on the new version available on Firefox. Thanks a lot. 😁
