### ISSUE TITLE
How to go to the next page?

### ISSUE THREAD

**Issue by geniusupgrader** [infokiller/google-search-navigator#6]
With the keyboard shortcuts, I can't reach the next page or the following pages.
Maybe right (next) and left (previous) should switch between the pages?

Unfortunately, it is also not working with [these Extensions](https://www.gtricks.com/google/automatically-load-next-google-search-results-page/).

**Comment by infokiller** [comment]
Currently indeed there is no way to go the next/previous pages.
I personally use vimium which has this feature for general websites and it also works in google search (`]]` for next, `]]` for previous).
I think it shouldn't be hard to do this- I'll update the issue once I start looking on implementing this.

**Comment by rik-smeets** [comment]
This issue is partly resolved by #5. That change makes it possibly to go to the next page, but not back. However the changes from #5 are not available in the Chrome Web Store yet.
