### ISSUE TITLE
Chrome plugin is not found

### ISSUE THREAD

**Issue by yoyoyousei** [infokiller/google-search-navigator#65]
google-search-navigator on chrome is not found on chrome extension store.
Is this eliminated from store?

link: https://chrome.google.com/webstore/detail/enhanced-keyboard-navigat/cohamjploocgoejdfanacfgkhjkhdkek

**Comment by infokiller** [comment]
See #60

**Comment by yoyoyousei** [comment]
oops, sorry for reporting duplicate issue.
thanks.
