### ISSUE TITLE
Wrongly focus on "Next Page" link and scroll to page bottom on Google Shopping in Firefox

### ISSUE THREAD

**Issue by toparchery** [infokiller/google-search-navigator#67]
Hello Michal,

It is latest FireFox 61.0.2 (64-bit) on Windows 7 SP1. When you make a search on google.com and click on Shopping tab, this extension will automatically focus on the "Next Page" of Shopping page and automatically scroll down to shopping page's very bottom. You have to scroll up every time.

We cannot find this issue on all other google pages.

Could you please fix this bug?

Thank you for your great extension! We love it!
Brian C.

**Comment by mancze** [comment]
The problem is that used selector does not match results on the shopping page and that option to focus first result item is enabled. The issue can be reproduced also in Chrome browser. The fix is to adjust selector so that it includes results on the shopping tab.

I will have a look at it.

**Comment by mcgeeco** [comment]
This is happening for me for regular search results on Chrome 68.0.3440.106.

**Comment by mancze** [comment]
@mcgeeco I think another user ran into same problem as reported in #73. Could you please provide the CSS path of the result link? Please reply to the mentioned issue, this one is about shopping results (which should be already fixed). Thanks.
