### ISSUE TITLE
Switch to images, Maps and the other "tabs"

### ISSUE THREAD

**Issue by geniusupgrader** [infokiller/google-search-navigator#7]
At the top of google there are these "tabs", don't know how you call them.
It would be awesome to switch from the search results to the images page from a shortcut, keeping the search input. So for example searching for "flowers" yield the (normal) list of webpages, hitting ctrl+right  and turning to the images page, would display pictures of flowers.
The shortcuts "ctrl+right" and "ctrl+left" are the ones I propose as default for switching between these "tabs".
Info: this feature is implemented in the DuckDuckGo search, altough only with "right" and "left" as keyboard shortcuts.

**Comment by infokiller** [comment]
Yes, I totally agree that this will be a useful feature. May take 1-2 weeks till I personally can get around to doing and testing this properly. I'll update this issue.

**Comment by rik-smeets** [comment]
@infokiller, what is your status on testing the changes of my pull request allowing this?

**Comment by infokiller** [comment]
@rik-smeets sorry for the delay, I'm now releasing the new version.

**Comment by infokiller** [comment]
Just released it, should be available in the webstore within an hour
