### ISSUE TITLE
Search results are not matched by the selector

### ISSUE THREAD

**Issue by bphi** [infokiller/google-search-navigator#73]
Ran into a problem where google.com changed the html structure of the results page slightly.

    [document.querySelectorAll('h3.r a'), (n) => n.parentElement.parentElement]

In extension.js was not picking up the new links. I added 

    [document.querySelectorAll('h3.LC20lb'), (n) => n.parentElement.parentElement.parentElement.parentElement]

to the SearchResultsCollection to fix the issue. Not sure if this is a temporary, or beta change by google, but I wanted to leave a record of my fix.

Thanks.

Edit: It doesn't seem "Open in a new tab" works with this fix.

**Comment by mancze** [comment]
Thanks for letting know. I think **mcgeeco** ran into [same problem](https://github.com/infokiller/google-search-navigator/issues/67#issuecomment-420900240).

**Comment by mcgeeco** [comment]
Thanks @mancze! Sorry for the stupid question, but how do I find the css path for the results page? Also by the way I should mention I'm still using the version that I got through the Chrome Store, so it's possibly out of date (ver 0.2.9).

**Comment by mancze** [comment]
No problem. If you are using Chrome, the easiest way is to actually capture the screenshot of the css path:

1. Right-click on the search result.
2. Select _Inspect_ .
3. Take screenshot of the element path. It's located as a bottom toolbar under the source code and looks like this:
![2018-09-13_1755](https://user-images.githubusercontent.com/1493286/45500268-94805200-b77e-11e8-9b13-947d7a77b22e.png)
(This is the actual path for my google result.)

**Comment by mcgeeco** [comment]
Great here it is:
![image](https://user-images.githubusercontent.com/5881581/45500800-6d725200-b777-11e8-9b82-98211388b4ba.png)

Let me know if I can provide anything else. (still Chrome `Version 69.0.3497.81 (Official Build) (64-bit)`)

**Comment by mancze** [comment]
Great, thanks. That's very helpful. I can see class did not change. Only structure is slightly modified. I think changing selector to `#search .r a` will work for both versions. Even containing parent is still two levels above, that's great.

**Comment by bphi** [comment]
@mancze are there any updates regarding a return to the chrome web store?

**Comment by mancze** [comment]
Sorry, I don't know. Try asking @infokiller - he is the maintainer for Chrome.

**Comment by infokiller** [comment]
@bphi see #60

**Comment by Polygonalr** [comment]
@mancze Setting the selector to `#search .r a` will cause the selector to pick up the "Cached" or "Similar" boxes as shown here. 
![test](https://user-images.githubusercontent.com/16399656/45591835-97529100-b990-11e8-9dcd-adb5ce57041e.png)
I believe having separate selectors for both versions of the page is the best.

**Comment by mancze** [comment]
I liked the PR #76 which solved the selector issue for both cases cleanly.
